In [2]:
import os
import pandas as pd
import numpy as np

from statistics import mean, stdev

from tqdm import tqdm
tqdm.pandas()

from sklearn.pipeline import Pipeline

/home/voloch/.local/lib/python3.7/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC

from sklearn.model_selection import cross_val_score, GridSearchCV

from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

/home/voloch/Anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [60]:
import nltk
#nltk.download('movie_reviews')
#nltk.download('stopwords')

from nltk.corpus import movie_reviews

In [4]:
PATH_TO_DATA = '/home/voloch/nltk_data/corpora/movie_reviews'
ANSW = './answers'

In [5]:
neg_ids = movie_reviews.fileids('neg')
pos_ids = movie_reviews.fileids('pos')

In [6]:
neg_feats = [movie_reviews.words(fileids=[f]) for f in neg_ids]

In [7]:
neg_feats[0]

['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...]

In [8]:
for f in neg_ids[:3]:
    print(f)

neg/cv000_29416.txt
neg/cv001_19502.txt
neg/cv002_17424.txt


In [9]:
len(neg_ids), len(pos_ids)

(1000, 1000)

In [10]:
all_reviews = []
all_ratings = []

In [11]:

for elmnt in tqdm(neg_ids):
    with open(os.path.join(PATH_TO_DATA, elmnt)) as fd:
        tmp_data = fd.read()
    all_reviews.append(tmp_data)
    all_ratings.append(0)
    
for elmnt in tqdm(pos_ids):
    with open(os.path.join(PATH_TO_DATA, elmnt)) as fd:
        tmp_data = fd.read()
    all_reviews.append(tmp_data)
    all_ratings.append(1)

100%|██████████| 1000/1000 [00:00<00:00, 4067.06it/s]


In [12]:
data = pd.DataFrame({'review': all_reviews, 'rating': all_ratings})

# WEEK 1

In [13]:
def write_answer_to_file(answer, file_address):
    if isinstance(answer, list) or isinstance(answer, np.ndarray):
        with open(os.path.join(ANSW, file_address), 'w') as out_f:
            for idx, elmnt in enumerate(answer):
                if idx == 0:
                    out_f.write(str(elmnt))
                else:
                    out_f.write(' ' + str(elmnt))
    else:
        with open(os.path.join(ANSW, file_address), 'w') as out_f:
            out_f.write(str(answer))

In [14]:
answ1 = data.shape[0]
write_answer_to_file(answ1, 'answer1_1.txt')
answ1

2000

In [15]:
answ2 = data[data.rating == 1].shape[0] / data.shape[0]
write_answer_to_file(answ2, 'answer1_2.txt')
answ2

0.5

In [16]:
CntVect = CountVectorizer()

In [17]:
CntVect.fit(data.review.values)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [18]:
answ3 = len(CntVect.get_feature_names())
write_answer_to_file(answ3, 'answer1_3.txt')
answ3

39659

In [19]:
X_train = CntVect.transform(data.review.values)

In [20]:
y_train = data.rating.values

In [21]:
model = LogisticRegression()

In [22]:
answ4 = cross_val_score(model, X_train, y_train, scoring = 'accuracy')
answ4 = sum(answ4) / len(answ4)
write_answer_to_file(answ4, 'answer1_4.txt')
answ4

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8360216503929078

In [23]:
model = LogisticRegression()

In [24]:
answ5 = cross_val_score(model, X_train, y_train, scoring = 'roc_auc')
answ5 = sum(answ5) / len(answ5)
write_answer_to_file(answ5, 'answer1_5.txt')
answ5

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9107764937833774

In [25]:
clf = LogisticRegression()

In [26]:
clf.fit(X_train, y_train)

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
len(CntVect.vocabulary_)

39659

In [28]:
len(CntVect.get_feature_names())

39659

In [29]:
answ_list = [(el0, el1) for el0, el1 in zip(CntVect.get_feature_names(),clf.coef_[0])]

In [30]:
answ_list.sort(key = lambda x: abs(x[1]), reverse = True)

In [31]:
answ_list[:10]

[('bad', -0.7821764060760804),
 ('unfortunately', -0.6366187395273799),
 ('worst', -0.5929017728150916),
 ('fun', 0.5560662269745028),
 ('waste', -0.5081787970026665),
 ('nothing', -0.5039886025418159),
 ('script', -0.4665341648847996),
 ('awful', -0.4652169088090188),
 ('boring', -0.4631910366092562),
 ('only', -0.4599571742679439)]

In [32]:
answ6 = []
for el, _ in answ_list[:2]:
    answ6.append(el)

write_answer_to_file(answ6, 'answer1_6.txt')
answ6

['bad', 'unfortunately']

# WEEK 2

In [33]:
stepsCntVect = [('vect', CountVectorizer()), ('lr', LogisticRegression())]
pipelCntVect = Pipeline(stepsCntVect)

In [34]:
stepsTfIdfVect = [('vecttf', TfidfVectorizer()), ('lr', LogisticRegression())]
pipelTfIdfVect = Pipeline(stepsTfIdfVect)

In [35]:
#answ2_1_1 = cross_val_score(pipelCntVect, data.review.values, y_train, scoring = 'accuracy', cv = 5)
answ2_1_1 = cross_val_score(pipelCntVect, data.review.values, y_train, cv = 5)
answ2_1_1

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs

array([0.815 , 0.84  , 0.8375, 0.8675, 0.845 ])

In [36]:
#answ2_1_2 = cross_val_score(pipelTfIdfVect, data.review.values, y_train, scoring = 'accuracy', cv = 5)
answ2_1_2 = cross_val_score(pipelTfIdfVect, data.review.values, y_train, cv = 5)
answ2_1_2

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs

array([0.8225, 0.825 , 0.825 , 0.815 , 0.8175])

In [37]:
answ2_1 = [mean(answ2_1_1), stdev(answ2_1_1), mean(answ2_1_2), stdev(answ2_1_2)]
write_answer_to_file(answ2_1, 'answer2_1.txt')
answ2_1

[0.841, 0.018758331482304103, 0.821, 0.004541475531146236]

In [39]:
paramCntVect = {
    'vect__min_df': [10, 50]
}

In [41]:
search = GridSearchCV(pipelCntVect, param_grid = paramCntVect, cv = 5)
answ2_2 = search.fit(data.review.values, y_train)
#answ2_2

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs

In [ ]:
#answ2_2 = cross_val_score(pipelCntVect, data.review.values, y_train, fit_params = paramCntVect, cv = 5)
#answ2_2

In [42]:
answ2_2.cv_results_

{'mean_fit_time': array([0.84378839, 0.75975132]),
 'std_fit_time': array([0.03091417, 0.05555115]),
 'mean_score_time': array([0.16563306, 0.14771352]),
 'std_score_time': array([0.00637133, 0.00462201]),
 'param_vect__min_df': masked_array(data=[10, 50],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'vect__min_df': 10}, {'vect__min_df': 50}],
 'split0_test_score': array([0.82  , 0.7925]),
 'split1_test_score': array([0.85 , 0.825]),
 'split2_test_score': array([0.8325, 0.8025]),
 'split3_test_score': array([0.8525, 0.8175]),
 'split4_test_score': array([0.84  , 0.8275]),
 'mean_test_score': array([0.839, 0.813]),
 'std_test_score': array([0.01189538, 0.01345362]),
 'rank_test_score': array([1, 2], dtype=int32)}

In [43]:
answ2_2.cv_results_['mean_test_score']
write_answer_to_file(answ2_2.cv_results_['mean_test_score'], 'answer2_2.txt')
answ2_2.cv_results_['mean_test_score']

array([0.839, 0.813])

In [68]:
CntVect = CountVectorizer()
CntVect.fit(data.review.values)
X_train = CntVect.transform(data.review.values)

In [69]:
clfLR = LogisticRegression()
resLR = cross_val_score(clfLR, X_train, y_train, cv = 5)
resLR

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.815 , 0.84  , 0.8375, 0.8675, 0.845 ])

In [70]:
clfSVC = LinearSVC()
resSVC = cross_val_score(clfSVC, X_train, y_train, cv = 5)
resSVC

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0.8025, 0.84  , 0.8325, 0.85  , 0.84  ])

In [71]:
clfSGD = SGDClassifier(loss='hinge', penalty='l2', alpha=0.0001, l1_ratio=0.15, 
                       fit_intercept=True, max_iter=5, shuffle=True, verbose=0, 
                       epsilon=0.1, n_jobs=1, random_state=42, learning_rate='optimal', 
                       eta0=0.0, power_t=0.5, class_weight=None, warm_start=False, average=False)
resSGD = cross_val_score(clfSGD, X_train, y_train, cv = 5)
resSGD

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


array([0.7175, 0.8075, 0.8375, 0.725 , 0.83  ])

In [72]:
answ2_3 = min([mean(resLR), mean(resSVC), mean(resSGD)])
write_answer_to_file(answ2_3, 'answer2_3.txt')
answ2_3

0.7835

In [62]:
len(nltk.corpus.stopwords.words('english'))

179

In [73]:
CntVect = CountVectorizer(stop_words=nltk.corpus.stopwords.words('english'))
CntVect.fit(data.review.values)
X_train_nltk = CntVect.transform(data.review.values)

In [74]:
clfstopwLR = LogisticRegression()
retnltkstopw = cross_val_score(clfstopwLR, X_train_nltk, y_train, cv = 5)
retnltkstopw

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.825 , 0.855 , 0.835 , 0.8475, 0.845 ])

In [76]:
CntVect = CountVectorizer(stop_words='english')
CntVect.fit(data.review.values)
X_train_sklearn = CntVect.transform(data.review.values)

In [77]:
clfstopw2LR = LogisticRegression()
retnltkstopw2 = cross_val_score(clfstopw2LR, X_train_sklearn, y_train, cv = 5)
retnltkstopw2

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.82  , 0.84  , 0.845 , 0.8425, 0.8475])

In [79]:
answ2_4 = [mean(retnltkstopw), mean(retnltkstopw2)]
write_answer_to_file(answ2_4, 'answer2_4.txt')
answ2_4

[0.8415, 0.839]

In [80]:
CntVect = CountVectorizer(ngram_range=(1, 2))
CntVect.fit(data.review.values)
X_train_wide_words = CntVect.transform(data.review.values)

In [82]:
clfLR_wide_word = LogisticRegression()
ret_wide_word = cross_val_score(clfLR_wide_word, X_train_wide_words, y_train, cv = 5)
ret_wide_word

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.8225, 0.8525, 0.8525, 0.87  , 0.865 ])

In [83]:
CntVect = CountVectorizer(ngram_range=(3, 5), analyzer='char_wb')
CntVect.fit(data.review.values)
X_train_wide_chars = CntVect.transform(data.review.values)

In [84]:
clfLR_wide_char = LogisticRegression()
ret_wide_char = cross_val_score(clfLR_wide_char, X_train_wide_chars, y_train, cv = 5)
ret_wide_char

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.8175, 0.8375, 0.815 , 0.8075, 0.8175])

In [85]:
answ2_5 = [mean(ret_wide_word), mean(ret_wide_char)]
write_answer_to_file(answ2_5, 'answer2_5.txt')
answ2_5

[0.8525, 0.819]

for myself

In [88]:
CntVect = CountVectorizer(ngram_range=(1, 2), stop_words=nltk.corpus.stopwords.words('english'))
CntVect.fit(data.review.values)
X_train_wide_words_n_stop = CntVect.transform(data.review.values)


clfLR_wide_word_n_stop = LogisticRegression()
ret_wide_word_n_stop = cross_val_score(clfLR_wide_word_n_stop, X_train_wide_words_n_stop, y_train, cv = 5)
ret_wide_word_n_stop

/home/voloch/Anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.8225, 0.8375, 0.8325, 0.865 , 0.86  ])

In [89]:
mean(ret_wide_word_n_stop)

0.8435

# WEEK 3